import type { Metadata } from "next";
import Image from "next/image";
import { PageHero, FeatureGrid } from "@/components/PageHero";
import { Reveal } from "@/components/Reveal";

export const metadata: Metadata={title:"Professionnels & industriels — HelioSolar",description:"Solutions photovoltaïques pour bâtiments tertiaires, industriels et agricoles."};

export default function Page(){
 const items=[{title:"Toitures d’activité",text:"Exploitez les grandes surfaces disponibles tout en tenant compte des charges, accès, équipements et contraintes d’exploitation.",metric:"36 à 500 kWc"},{title:"Industrie",text:"Réduisez les charges énergétiques avec une production dimensionnée autour des courbes de consommation du site."},{title:"Agriculture",text:"Valorisez hangars, bâtiments d’élevage et foncier avec une approche adaptée aux contraintes agricoles."},{title:"Ombrières",text:"Combinez protection, production et valorisation des parkings sans immobiliser de nouvelle emprise au sol."},{title:"Étude économique",text:"Analyse de consommation, scénarios d’autoconsommation, production estimée et lecture des leviers de rentabilité."},{title:"Pilotage de projet",text:"Coordination technique, documentation, exécution et contrôle qualité avec un interlocuteur identifié."}];
 return <><PageHero eyebrow="Professionnels & industriels" title="Transformez vos surfaces en actif énergétique." description="HelioSolar conçoit des installations photovoltaïques robustes, lisibles et adaptées aux contraintes réelles de votre activité."/>
 <section className="py-20"><div className="container-px"><Reveal><div className="grid gap-5 lg:grid-cols-[1.25fr_0.75fr]"><div className="relative min-h-[420px] overflow-hidden rounded-5xl shadow-panel"><Image src="/media/realisation-industrial.svg" alt="Grande toiture photovoltaïque professionnelle" fill unoptimized className="object-cover" sizes="(min-width: 1024px) 65vw, 100vw"/><div className="absolute inset-0 bg-gradient-to-t from-ocean-950/65 via-transparent to-transparent"/><div className="absolute bottom-7 left-7 text-white"><p className="text-xs font-bold uppercase tracking-[0.2em] text-solar-300">Réalisations réelles</p><p className="mt-2 max-w-xl text-2xl font-bold">Des grandes surfaces exploitées avec une implantation précise.</p></div></div><div className="grid gap-5"><div className="relative min-h-[200px] overflow-hidden rounded-4xl"><Image src="/media/hero-agri.svg" alt="Bâtiment photovoltaïque en environnement agricole" fill unoptimized className="object-cover" sizes="(min-width: 1024px) 35vw, 100vw"/></div><div className="relative min-h-[200px] overflow-hidden rounded-4xl"><Image src="/media/realisation-industrial.svg" alt="Hangar agricole couvert de panneaux photovoltaïques" fill unoptimized className="object-cover" sizes="(min-width: 1024px) 35vw, 100vw"/></div></div></div></Reveal></div></section>
 <section className="pb-24 sm:pb-28"><div className="container-px"><FeatureGrid items={items}/></div></section></>;
}
